### ISSUE TITLE
MacOS compilation works fine

### ISSUE THREAD

**Issue by ScriptJunky** [McSib/e621_downloader#28]
[REDACTED]

**Comment by ScriptJunky** [comment]
![Screen Shot 2020-01-04 at 3 18 15 AM](https://user-images.githubusercontent.com/14885339/71762759-72de3900-2ea1-11ea-84ff-3f01d2f36ce3.png)

**Comment by ScriptJunky** [comment]
![Screen Shot 2020-01-04 at 3 18 15 AM](https://user-images.githubusercontent.com/14885339/71762947-13355d00-2ea4-11ea-8720-45ed5d6fc731.png)

**Comment by McSib** [comment]
It's good to hear that the program is working fine on Mac! I would like to ask a question though:

> 
> 
> [e621_downloader.zip](https://github.com/McSib/e621_downloader/files/4021681/e621_downloader.zip)

Is the file given here the Mac executable?

**Comment by ScriptJunky** [comment]
It is. Github has attachment restrictions, which is sane and expected.

**Comment by McSib** [comment]
If I'm not mistaken, isn't the file extension for Mac executables `.dmg`? It seems when I open the zip, there is a file with my program's name, attaching the `.7z` extension to it shows a lot of other data. I'm assuming the file in the zip is the executable for Mac. Since I'm not fluent with the OS, only having a little bit of experience, so I apologize if I'm wrong. I'm happy that my program works on Mac though, it's nice to know that there isn't any compatibility issues with it. 😄

**Comment by ScriptJunky** [comment]
dmg is used on MacOS for package installation bundles. A dmg is mounted in MacOS like a disk, and there would be a folder inside containing all relevant files for the bundled app. The folder is generally named <application>.app and can be dragged directly into /Applications on MacOS. 

In this case, since this is just a rust binary (and one that runs from cli at that), there is nothing to bundle.

**Comment by ScriptJunky** [comment]
Actually, after running strings against the extracted file, I see that when compiling Rust leaks a metric ton of pathing info that I would much prefer NOT be a part of the binary at all. Can you delete the zip and I will recompile where it won't include my homedir path?

**Comment by McSib** [comment]
> 
> 
> @McSib Actually, after running a certain unix command against the extracted file, I see that when compiling a Rust binary it leaks a metric ton of pathing info (/Users/<username>) that I would much prefer NOT be a part of the binary at all. Can you delete the zip and I will recompile where it won't include my homedir path?

Sorry for the cheesy edit I did, it's the only thing I could think off after writing a bunch of documentation for the project. That should do it though.

**Comment by McSib** [comment]
> 
> 
> dmg is used on MacOS for package installation bundles. A dmg is mounted in MacOS like a disk, and there would be a folder inside containing all relevant files for the bundled app. The folder is generally named <application>.app and can be dragged directly into /Applications on MacOS.
> 
> In this case, since this is just a rust binary (and one that runs from cli at that), there is nothing to bundle.

And I didn't know that! I've been on Windows since I was a kid, so this OS is my bread and butter. I have dabbled in Mac's shell a few times, but I tend to have more experience in Linux than Mac, on account I had moved to Linux once and had a VM of it for a while.

**Comment by ScriptJunky** [comment]
@McSib Thanks much for the quick delete! 

Once I get back home (on vacation) I'll repoint ~/.cargo and recompile, and provide a fresh binary.

**Comment by McSib** [comment]
> 
> 
> @McSib Thanks much for the quick delete!
> 
> Once I get back home (on vacation) I'll repoint ~/.cargo and recompile, and provide a fresh binary.

It would be much appreciated since 1.5.3 is almost done. Enjoy your vacation!

**Comment by McSib** [comment]
1.5.4 is out and ready to use. So be sure to download the source of the release below before compiling, so that way you're running the latest version!

https://github.com/McSib/e621_downloader/releases/tag/v1.5.4

**Comment by ScriptJunky** [comment]
```
iMac➜~» strings e621_downloader | grep -i e621_dow                                                                                                                                                                                  [18:08:58]
e621_downloader/1.5.4 (by McSib on e621)
iMac➜~»
```

```
iMac➜~» shasum e621_downloader                                                                                                                                                                                                      [18:09:52]
a616a5d65bec9cb5ca1f407f623f13e958e5d8f8  e621_downloader
iMac➜~»
```

[e621_downloader.zip](https://github.com/McSib/e621_downloader/files/4050040/e621_downloader.zip)

**Comment by McSib** [comment]
Thank you for supplying the build! Would you be okay if I used this on the release page for Mac users to download and use? I imagine there are a few that would love to use my software since Mac support for downloaders are limited right now. 😸

**Comment by ScriptJunky** [comment]
@McSib Yeah that's fine. I compiled this one outside of `~/` and after it was built I ensured that sensitive pathing info was no longer present.

**Comment by McSib** [comment]
That's good, the new build will be supplied shortly, currently reading a lot of Rust API for some optimizations.

**Comment by McSib** [comment]
Your build has been put up with the Windows build. Thanks for building it, I'm sure many users will be happy to see and use it!
