### ISSUE TITLE
Pools with non-filename-allowed characters in their name fail to download

### ISSUE THREAD

**Issue by Nightscale54** [McSib/e621_downloader#37]
Pools with colon in the name, like "ExamplePool: Chapter 1" are not downloaded correctly. The download folder for the pool is created correctly and the program seems to download files without giving any errors, however the folder will only contain one 0 byte file with the filename being whatever the pool name is before the colon, which in this case it would be "ExamplePool". 

Also pools with quotes in the name, like "The "example" pool" are not downloaded correctly. Again the folder seems to be created correctly but the program will panic while downloading the first file and exit with a syntax error. No files are created in this case.

While I did not test this I assume pool names with other characters not allowed in filenames would also cause similar problems.

**Comment by McSib** [comment]
Sorry I haven't gotten to your question in a bit, I've been busy with financial issues, but it appears that somehow the name of the pool is getting through the invalid character check when it's creating the folders. More than likely it's something to do on my side. I know a pull request has been made to fix this issue, but from what I could gather on a surface check its placement was in a spot where I wouldn't put it. I normally only modify the strings with an invalid character check right before the image creation, before the post itself is disposed of in memory. So I'll see what I can do soon, I'm more than likely going to modify the pull request slightly before I actually allow it to go through and sync with the main branch.

**Comment by McSib** [comment]
This issue has been fixed in an upcoming hotfix, so this can now be put to rest, sorry for the update taking so long!
