### ISSUE TITLE
Pool filename numbering issue

### ISSUE THREAD

**Issue by Nightscale54** [McSib/e621_downloader#41]
After updating from 1.6.0 to 1.6.1 pool filename numbering seems to be messed up a bit.
Before it was file0001, file0002, file0003, ... file0009, file0010, file0011 and so on.
Now it is file1000, file2000, file3000, ... file9000, file1000, file1100 and so on.

**Comment by McSib** [comment]
This was an issue that was found out shortly after release, I've already fixed it, but I'm working on a few other features before releasing the next version. I'll make sure to double-check so there won't be a sorting issue with this upcoming release.
