### ISSUE TITLE
Works flawlessly on Linux

### ISSUE THREAD

**Issue by KingAbyx** [McSib/e621_downloader#42]
This is not an issue, but I don't know a better place to put this. I compiled Version 1.6.1 on my Arch Linux system and it works perfectly

**Comment by Krutonium** [comment]
Confirmed.

**Comment by McSib** [comment]
Hey, sorry for the late reply as some personal stuff in my life took priority, but I'm happy to hear it worked well for you! When I was developing the software I kept in mind and made my intentions clear to try and make sure it compiled and worked fine for Linux. I couldn't test it directly, but I was making sure my code was completely compatible with Linux distros by avoiding libraries that were directed mainly towards Windows. Happy to hear my method paid off well :3

**Comment by Krutonium** [comment]
Any reply, even a late one, is better than no reply at all.

**Comment by McSib** [comment]
I will be closing this discussion and freeing up the issue board some for cleanup. Thank you both for your kind words; I hope you both have a good day :3
