### ISSUE TITLE
Does not work when logged in

### ISSUE THREAD

**Issue by Earlopain** [McSib/e621_downloader#44]
As reported in the forum thread:

I recently removed `appeal_count` from the api response, which breaks serde deserialization. Just removing the field from the struct should work fine as a fix.

**Comment by McSib** [comment]
Thanks for notifying me on this issue, I'll update the program here shortly with the fix.

**Comment by McSib** [comment]
This issue is now fixed with the latest commit; an upcoming release will be out shortly (estimated 1-2 hours).
