### ISSUE TITLE
Program doesn't seem to respect the "config.json" file after the 1.7.0 update

### ISSUE THREAD

**Issue by DestinyPlayer** [McSib/e621_downloader#45]
My current config is this:
`{
  "downloadDirectory": "D:/e621/"
}`

Before the update, my folder structure looked like this:
`[Program Root]/D_/e621/General Searches`

After the update, it now looks like this:
`[Program Root]/General Searches`

Not sure if this is an intended change or something unforeseen, but it's ought to be reported regardless, since there was nothing about it in the changelog

**Comment by McSib** [comment]
I'll have to take a look at it through my own testing, it seems as if something with your download directory is glitching the program into not creating the directories appropriately. There were a lot of performance-based changes that I did behind the scenes as well, maybe one of the ones I added ended up messing with how the directories were created.

**Comment by DestinyPlayer** [comment]
If it helps with the testing, Disk D: on my computer is an external hard drive.

Probably nothing, but who knows, with such bugs on such a low-level program, anything could be an issue.

**Comment by McSib** [comment]
I know that the program is intended to create a directory at the program's root directory. However, it should make the download directory without an issue. In the case you showed, something with the download directory just broke how it does it and thought the program's root directory _was_ the download directory. That is undefined behavior that I need to look into and correct. It's weird that it's happening as I don't think I modified the code for it at all, but I may be wrong.

**Comment by McSib** [comment]
I created a hotfix branch and will work on correcting this issue. It should be fixed within an hour or two.

**Comment by DestinyPlayer** [comment]
Thank you. Unfortunately I'd already moved all of my stuff into the other folder (since it wasn't really going where I intended it to go regardless so might as well simplify it), but hopefully this might help others, if nothing else.

**Comment by McSib** [comment]
So, I did a test with your same config setup (as I have a program drive under `D:`). In my case, it saved the downloads into the `D:` drive, inside the `e621` folder correctly. This behavior seems pretty normal, but I'm going to look into the code and see if there is anything different there.

**Comment by McSib** [comment]
Would you mind sharing your logfile with that configuration? I might get more information from there.

**Comment by DestinyPlayer** [comment]
`01:20:37 [TRACE] (1) e621_downloader::program: [src\program.rs:18] Starting downloader...
01:20:41 [INFO] Read tag file...
01:20:41 [TRACE] (1) e621_downloader::program: [src\program.rs:35] Parsed tag data, now attempting to obtain user blacklist...
01:20:41 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:72] Initializing blacklist parser...
01:20:41 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:83] Parsing blacklist...
01:20:41 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:94] Parsed blacklist...
01:20:41 [TRACE] (1) e621_downloader::program: [src\program.rs:40] Parsed and processed user blacklist...
01:20:41 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:93] Grabbing posts...
01:20:42 [INFO] [38;5;39m[3m"fav:system_searcher"[0m grabbed!
01:21:06 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:412] No posts filtered...
01:21:10 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:412] No posts filtered...
01:21:35 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:412] No posts filtered...
01:22:05 [TRACE] (1) e621_downloader::e621::blacklist: [src\e621\blacklist.rs:412] No posts filtered...
01:22:05 [INFO] [38;5;39m[3m"female krystal order:score -rating:safe"[0m grabbed!
01:38:55 [INFO] Finished downloading posts!
01:38:55 [INFO] Exiting...
`
`# This is the tag file that you will use so the program can know what tags to search.
# If you wish to comment in this file, simply put `#` at the beginning or end of line.

# Insert tags you wish to download in the appropriate group (remove all example tags and IDs with what you wish to download):

[artists]

[pools]


[sets]


[single-post]


[general]
female krystal order:score -rating:safe`
Doesn't seem to have any more info than what I'd already relayed, but here you go.

**Comment by McSib** [comment]
After taking time to really test this issue, I've found nothing pointing to the program directly causing this issue. I have a drive under the letter `D:`, through my testing, images were saved to this drive correctly.

I also decided to see if maybe the drive wasn't being seen in the program, so I changed my download directory from `D:` to `P:`. This actually crashed the program with this error:
```
01:24:27 [ERROR] Could not create directories for images!
01:24:27 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:137] Directory path unable to be created...
01:24:27 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:138] Path: "P:/e621/fav_McSib"
```

This tells me that the program would crash if your external hard drive wasn't detected. But it only furthers my confusion on what's happening with your downloads. I also tested with your tag file and had no issues with parsing and downloading. All of it saved in `D:\e621\General Searches\female krystal order_score -rating_safe` without any issue.

My next question for you is actually pretty important as it will tell me exactly what might be happening. Are you using Windows, Linux, or Mac? I have experience with Windows and Linux, I'm more unfamiliar with Mac. Something I do know however is that Linux has an interesting way of handling drives, and if you're using Linux, that might help me figure out what's happening on a better level. Currently, there just seems to not be enough information about what's happening. The logging system is very new, so it's bound to be light on information right now. But I think a good first step is knowing what OS you are on currently, as this saving pattern isn't fitting to anything I'm used to with Windows.

**Comment by McSib** [comment]
I've created a modified version of 1.7.0 with a lot more information in the logger. Run this program with the setup you have and then send me the log file. This will tell me exactly what's happening. Thanks for being patient with me. I'm just as confused about what's happening right now.

[e621_downloader.1.7.0-hotfix-test.zip](https://github.com/McSib/e621_downloader/files/8191845/e621_downloader.1.7.0-hotfix-test.zip)

**Comment by DestinyPlayer** [comment]
Hadn't yet tried the modified version, but my OS is Windows 10, Ver. 21H1, if it helps.

**Comment by McSib** [comment]
There is something else that may be happening. From what you've been explaining, it sounds like you have your exe is inside of `D:/e621/`. If that's the case, your program isn't having any problems. I did do a modification to the program a while back, and what it essentially did was it stopped removing characters from the download directory. It made it so people could hardwire paths to separate directories without having it constantly be at the program's root directory. So it may actually be downloading the images correctly, but it might just be doing it different from what you expected. The way it's set up right now isn't to convert `D:/e621/` to `D_/e621/`. What it's actually supposed to do is to lay down the path directly to where you're pointing it. So if it's set to download images in that directory on that drive, it's going to do exactly that.

**Comment by DestinyPlayer** [comment]
Huh. Let me try testing that, if that's the case it might have been broken BEFORE and got fixed NOW.

**Comment by DestinyPlayer** [comment]
That is indeed the case now. It was broken before the update, and now it actually detects the path correctly.

**Comment by McSib** [comment]
Okay, so there's no issue here? I just want to make sure, and it's no problem at all, I was wondering about it and figured that you might have had the executable inside of the directory you were trying to save the images too haha. So you're good 😊

**Comment by McSib** [comment]
I'll go ahead and mark this issue as closed. If there is still something wrong here, feel free to reopen the issue, and I'll jump on it. Have a good night!
