### ISSUE TITLE
Naming posts by their id

### ISSUE THREAD

**Issue by mithrilarmor** [McSib/e621_downloader#47]
Is it possible to configure to name all downloaded posts by their id instead of md5? It would be ideal to sort them by their id so they could be listed chronologically once downloaded. That would be especially useful for huge folders with hundreds or even thousands of posts to have them listed like on e621. That way they could be sorted form the first artists work to the latest or vice versa. I personally download posts by artists only.

**Comment by McSib** [comment]
I can add this in the next version for you, it shouldn't be too difficult to do something like that.

**Comment by mithrilarmor** [comment]
Thank you, that would be great because with current version I can mass download posts for archiving but to actually browse them would be a nightmare without some way to organize them. At least with their proper post names they could be sorted by their posting order and browse through them like on e621.

**Comment by mithrilarmor** [comment]
Previously I have used DonovanMC e621 downloader which did its job well enough considering its way of downloading. But since the start of this year it just stopped functioning so I've just recently searched for an alternative. Your solution is far superior as it does not require installation, consumes tiny amount of storage and as it works with a tag list it immensely eases download process by skipping already downloaded posts and gets only new or missing ones. The best of all it works with double click on executable and it does it all.

**Comment by McSib** [comment]
I originally made this program back when there were two primary downloaders, one of which was a pool downloader and the other was just a python script for general searching. I made this program essentially to make downloading more robust and accessible without the need to search for five different programs that handled separate areas. My want was for an "all-in-one" downloader that worked out-of-the-box and was extremely fast. All the downloads happen on a single thread, and just that has outperformed every other downloader from my testing. I'm happy where the program is at nowadays, and hope to see it go further as I add more and keep it up-to-date. Thanks for the kind words. I'm working on getting your feature added right now :3

**Comment by McSib** [comment]
This feature is now added, will be released in the next update. Have a good day/night!
