### ISSUE TITLE
Downloader randomly crashes in the middle of grabbing the tags

### ISSUE THREAD

**Issue by DestinyPlayer** [McSib/e621_downloader#48]
Ever since today, the program just started to randomly crash in the middle of grabbing all the tags. Sometimes it crashes at the very start, sometimes it's in the middle, sometimes it's at the very end, but there's always some sort of error like this.

```04:52:54 [ERROR] Unable to deserialize json to "alloc::vec::Vec<e621_downloader::e621::sender::entries::PostEntry>"!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

error decoding response body: expected value at line 1 column 1', src\e621\sender\mod.rs:290:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

Let me see if I can get a proper log generated, it seems to cut off at that error, not even finishing it printing, I only managed to get this via running the app in command line.

**Comment by DestinyPlayer** [comment]
```
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:23] Printing system information out into log for debug purposes...
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:24] ARCH:           "x86_64"
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:25] DLL_EXTENSION:  "dll"
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:26] DLL_PREFIX:     ""
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:27] DLL_SUFFIX:     ".dll"
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:28] EXE_EXTENSION:  "exe"
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:29] EXE_SUFFIX:     ".exe"
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:30] FAMILY:         "windows"
04:56:59 [TRACE] (1) e621_downloader: [src\main.rs:31] OS:             "windows"
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:26] Starting e621 downloader...
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:27] Program Name: e621_downloader
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:28] Program Version: 1.7.0-hotfix.1
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:29] Program Authors: McSib <mcsibsart@gmail.com>
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:30] Program Working Directory: D:\e621
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:39] Checking if config file exists...
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:47] Checking if tag file exists...
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:61] Login information loaded...
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:62] Login Username: system_searcher
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:63] Login API Key: ************************
04:56:59 [TRACE] (1) e621_downloader::program: [src\program.rs:64] Login Download Favorites: true
04:56:59 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:54] SenderClient initializing with USER_AGENT_VALUE "e621_downloader/1.7.0-hotfix.1 (by McSib <mcsibsart@gmail.com> on e621)"
04:56:59 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:59] Prompt for safe mode...
04:57:01 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:72] Safe mode decision: false
04:57:01 [TRACE] (1) e621_downloader::program: [src\program.rs:71] Parsing tag file...
04:58:19 [ERROR] Json was unable to deserialize to "serde_json::value::Value"!
04:58:19 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:320] url_type_key: tag_bulk
04:58:19 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:321] tag: long_playtime
```
Here's what the log gives me when it crashes at the very beginning.

**Comment by McSib** [comment]
That's a weird one, however, I know the developers right now are cleaning up the REST API responses for e621/e926, so I will take a look and see what's happening. It's crashing during the parsing phase, and it's crashing on the first tag lookup, so I will look into that and see what the API is responding with.

**Comment by McSib** [comment]
Are you using a VPN by chance? There was an issue similar to this in the past but the person was using a VPN that was reacting weirdly with the downloader (causing crashing during downloads, crashing during parsing, stalling with certain files for a long time).

**Comment by DestinyPlayer** [comment]
I am using a VPN, however before today there were no issues like this.

And unfortunately, due to local website blacklist reasons, not using a VPN is not actually an option.

**Comment by McSib** [comment]
In issue #27 which you can view, there is currently a rare problem that can happen that is completely independent of my program. Cloudflare, when using a VPN, will sometimes prompt if you are a robot. Basically, a captcha appears where I should be receiving data from the API. This is something that will crash my program. Try switching your VPN to another country (if possible) and see if that fixes it. This was an issue I investigated thoroughly on #27 and I have no way of bypassing since Cloudflare is e621 security for their site. It happens occasionally, and I think it's rare overall.

**Comment by McSib** [comment]
https://github.com/McSib/e621_downloader/issues/27#issuecomment-573323636

This comment here describes exactly what I'm talking about. It doesn't have to be a Russian specific VPN either. I think this is something that just happens in general.

**Comment by DestinyPlayer** [comment]
Huh. Then I wonder why it was that I was suddenly struck with it yesterday, to the point that across several hours it just kept repeatedly happening, when it hadn't happened at all once before then. Interesting luck I guess.

**Comment by McSib** [comment]
I'm not too sure on what causes it, but I think it's when the same IP from the VPN connects to a Cloudflare server repeatedly, similar to a DDOS. If it happens enough times Cloudflare requires a manual verification that you're not a bot. It's very spontaneous when issues like that happen and you can't really predict it. It's all dependent really on how the Cloudflare firewall feels. Tell me if that fixes it when you have time to test it. If it does then that's the issue.

**Comment by DestinyPlayer** [comment]
All right, seems to have worked now. Let's hope this doesn't repeat too often.

**Comment by McSib** [comment]
I don't think it will, the last person hasn't posted about it since they found the fix. Glad it worked though! Have a good rest of the day/night.
