### ISSUE TITLE
Tag with a colon in it causes a crash

### ISSUE THREAD

**Issue by xcloudx01** [McSib/e621_downloader#51]
Trying to download the tag "mao_mao:_heroes_of_pure_heart" results in the following error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\e621\io\tag.rs:162:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I assume it's because it's got a colon in the name?

**Comment by xcloudx01** [comment]
Fantastic work btw! It's been working flawlessly up until now. Figured I'd best report the bug :3

**Comment by McSib** [comment]
Could you send me the log file? It should be in the same directory with your program.

**Comment by McSib** [comment]
> Fantastic work btw! It's been working flawlessly up until now. Figured I'd best report the bug :3

Thanks for the kind words! I put a lot of work into it :3

**Comment by LancersBucket** [comment]
I'm having a similar issue, but instead the error that it displays is: `thread 'main' panicked at 'internal error: entered unreachable code', src\e621\grabber.rs:189:38`
This is when I'm trying to download an artist with the tag "rating:questionable"
The stack backtrace is below:
```
stack backtrace:
   0:           0x9a80fb - std::backtrace_rs::backtrace::dbghelp::trace::h81f68c85e8a404bc
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98:5
   1:           0x9a80fb - std::backtrace_rs::backtrace::trace_unsynchronized::h38c8cbf83a2b340b
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66:5
   2:           0x9a80fb - std::sys_common::backtrace::_print_fmt::he83f99e5e7da91ec
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:67:5
   3:           0x9a80fb - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdca2d1f25a396476
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:46:22
   4:           0xa12eeb - core::fmt::write::h15a44803aaa8cb9c
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\core\src\fmt\mod.rs:1078:17
   5:           0x999d93 - std::io::Write::write_fmt::h30650b0792e7e471
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\io\mod.rs:1518:15
   6:           0x9abd08 - std::sys_common::backtrace::_print::h8a896f01a2594c13
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:49:5
   7:           0x9abd08 - std::sys_common::backtrace::print::hdd949e22ad060cf7
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:36:9
   8:           0x9abd08 - std::panicking::default_hook::{{closure}}::h7c4d2996f576da8d
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:208:50
   9:           0x9ab925 - std::panicking::default_hook::h6bfae4e54c8522ba
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:225:9
  10:           0x9ac599 - std::panicking::rust_panic_with_hook::h39f01e8db1be2ade
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:591:17
  11:           0x9ac108 - std::panicking::begin_panic_handler::{{closure}}::h86dd34af0246fff3
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:495:13
  12:           0x9a8acf - std::sys_common::backtrace::__rust_end_short_backtrace::h355dac0ec8174c13
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:141:18
  13:           0x9ac099 - rust_begin_unwind
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:493:5
  14:           0xa0ef90 - core::panicking::panic_fmt::h1d1211160fcdc80c
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\core\src\panicking.rs:92:14
  15:           0xa0eedc - core::panicking::panic::ha265801377b91576
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\core\src\panicking.rs:50:5
  16:           0x5a4e4f - e621_downloader::e621::grabber::Grabber::grab_posts_by_tags::h08e56b6309e85e9c
  17:           0x5df62c - e621_downloader::main::h1736d3c63a77888f
  18:           0x5e3db6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e56d6c100bb1f1b
  19:           0x5e3f7d - std::rt::lang_start::{{closure}}::h4cb33a289be0172f
  20:           0x9ac81c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h137dc4e3949337b2
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\library\core\src\ops/function.rs:259:13
  21:           0x9ac81c - std::panicking::try::do_call::h0e5552fee324fdbb
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:379:40
  22:           0x9ac81c - std::panicking::try::h6d54d70d12e29c0a
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:343:19
  23:           0x9ac81c - std::panic::catch_unwind::h8e874b49d2127ff8
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panic.rs:396:14
  24:           0x9ac81c - std::rt::lang_start_internal::h79337b5f0625a1d5
                               at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\rt.rs:51:25
  25:           0x5e0248 - main
  26:           0x57142a - __tmainCRTStartup
  27:           0x57113d - mainCRTStartup
  28:     0x7ff990437034 - <unknown>
  29:     0x7ff9912c2651 - <unknown> 
  ```
  Hope this helps

**Comment by McSib** [comment]
> I'm having a similar issue, but instead the error that it displays is: `thread 'main' panicked at 'internal error: entered unreachable code', src\e621\grabber.rs:189:38`
> This is when I'm trying to download an artist with the tag "rating:questionable"
> The stack backtrace is below:
> ```
> stack backtrace:
>    0:           0x9a80fb - std::backtrace_rs::backtrace::dbghelp::trace::h81f68c85e8a404bc
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98:5
>    1:           0x9a80fb - std::backtrace_rs::backtrace::trace_unsynchronized::h38c8cbf83a2b340b
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66:5
>    2:           0x9a80fb - std::sys_common::backtrace::_print_fmt::he83f99e5e7da91ec
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:67:5
>    3:           0x9a80fb - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdca2d1f25a396476
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:46:22
>    4:           0xa12eeb - core::fmt::write::h15a44803aaa8cb9c
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\core\src\fmt\mod.rs:1078:17
>    5:           0x999d93 - std::io::Write::write_fmt::h30650b0792e7e471
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\io\mod.rs:1518:15
>    6:           0x9abd08 - std::sys_common::backtrace::_print::h8a896f01a2594c13
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:49:5
>    7:           0x9abd08 - std::sys_common::backtrace::print::hdd949e22ad060cf7
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:36:9
>    8:           0x9abd08 - std::panicking::default_hook::{{closure}}::h7c4d2996f576da8d
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:208:50
>    9:           0x9ab925 - std::panicking::default_hook::h6bfae4e54c8522ba
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:225:9
>   10:           0x9ac599 - std::panicking::rust_panic_with_hook::h39f01e8db1be2ade
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:591:17
>   11:           0x9ac108 - std::panicking::begin_panic_handler::{{closure}}::h86dd34af0246fff3
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:495:13
>   12:           0x9a8acf - std::sys_common::backtrace::__rust_end_short_backtrace::h355dac0ec8174c13
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\sys_common\backtrace.rs:141:18
>   13:           0x9ac099 - rust_begin_unwind
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:493:5
>   14:           0xa0ef90 - core::panicking::panic_fmt::h1d1211160fcdc80c
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\core\src\panicking.rs:92:14
>   15:           0xa0eedc - core::panicking::panic::ha265801377b91576
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\core\src\panicking.rs:50:5
>   16:           0x5a4e4f - e621_downloader::e621::grabber::Grabber::grab_posts_by_tags::h08e56b6309e85e9c
>   17:           0x5df62c - e621_downloader::main::h1736d3c63a77888f
>   18:           0x5e3db6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e56d6c100bb1f1b
>   19:           0x5e3f7d - std::rt::lang_start::{{closure}}::h4cb33a289be0172f
>   20:           0x9ac81c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h137dc4e3949337b2
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\library\core\src\ops/function.rs:259:13
>   21:           0x9ac81c - std::panicking::try::do_call::h0e5552fee324fdbb
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:379:40
>   22:           0x9ac81c - std::panicking::try::h6d54d70d12e29c0a
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panicking.rs:343:19
>   23:           0x9ac81c - std::panic::catch_unwind::h8e874b49d2127ff8
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\panic.rs:396:14
>   24:           0x9ac81c - std::rt::lang_start_internal::h79337b5f0625a1d5
>                                at /rustc/fde692739576089729885b7f79aa2232cb9778c5\/library\std\src\rt.rs:51:25
>   25:           0x5e0248 - main
>   26:           0x57142a - __tmainCRTStartup
>   27:           0x57113d - mainCRTStartup
>   28:     0x7ff990437034 - <unknown>
>   29:     0x7ff9912c2651 - <unknown> 
>   ```
>   Hope this helps

Could you supply the `e621_downloader.log` file? It contains much more detailed information as well as the error. It will help me understand what the exact circumstances were as well as system information to properly debug everything.

**Comment by LancersBucket** [comment]
@McSib Is there supposed to be a log file generated? I do not see any in the folder where the program is. I believe I am on version 1.6.1

**Comment by McSib** [comment]
> @McSib Is there supposed to be a log file generated? I do not see any in the folder where the program is. I believe I am on version 1.6.1 

Please update to the latest release and try downloading your posts again. If the error occurs, you should have a log file you can send me. I introduced it in the latest version for debugging purposes and it helps me understand the exact circumstances to what lead to the bug.

**Comment by LancersBucket** [comment]
I just updated to the latest version, and the error still occurs. The new error in the terminal says
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\e621\io\tag.rs:162:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The log file is included below
```
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:23] Printing system information out into log for debug purposes...
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:24] ARCH:           "x86_64"
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:25] DLL_EXTENSION:  "dll"
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:26] DLL_PREFIX:     ""
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:27] DLL_SUFFIX:     ".dll"
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:28] EXE_EXTENSION:  "exe"
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:29] EXE_SUFFIX:     ".exe"
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:30] FAMILY:         "windows"
13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:31] OS:             "windows"
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:26] Starting e621 downloader...
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:27] Program Name: e621_downloader
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:28] Program Version: 1.7.0-hotfix.1
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:29] Program Authors: McSib <mcsibsart@gmail.com>
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:30] Program Working Directory: C:\Users\Andrew\Downloads\e_downloader_1.7.0-hotfix.1_release
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:39] Checking if config file exists...
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:47] Checking if tag file exists...
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:61] Login information loaded...
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:62] Login Username: 
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:63] Login API Key: 
13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:64] Login Download Favorites: true
13:35:56 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:54] SenderClient initializing with USER_AGENT_VALUE "e621_downloader/1.7.0-hotfix.1 (by McSib <mcsibsart@gmail.com> on e621)"
13:35:56 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:59] Prompt for safe mode...
13:35:58 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:72] Safe mode decision: false
13:35:58 [TRACE] (1) e621_downloader::program: [src\program.rs:71] Parsing tag file...
```

**Comment by DestinyPlayer** [comment]
My assumption is that it's trying to read the tag as if it was one of the system tags, like rating:safe or order:rating

**Comment by McSib** [comment]
By question, do you happen to be running a VPN? There is a present issue that is unfixable on my side, _[#47]_ and _[#27]_ are both examples of a VPN crashing the program unexpectedly. This is something I _cannot_ repair if it's the case. I have talked with others, and looked into it, and it's a Cloudflare protection service that will prompt the user to answer a captcha. Since my client is console based, there is no way for the user to authenticate, thus crashing the program. From what I know, this protection protocol is triggered when the IP is considered suspicious. This is done a lot with VPNs sadly.

A temporary solution to this issue is to switch locations in your VPN. Your requests will start working without an issue, but it may resurface. To fix it, just switch to another location. You're going to have to do this until Cloudflare incorporates a way for users to authenticate through console programs.

**Comment by McSib** [comment]
I have tested to try and replicate the issues, using searches with `order:score` and `rating:safe` both in the search, and had no issue. The only time I've seen this error happen is with VPNs being "captchaed" by Cloudflare.

**Comment by McSib** [comment]
> [e621_downloader.log](https://github.com/McSib/e621_downloader/files/8465076/e621_downloader.log)

Now that I've replied to the others, I can work on your issue, which I can replicate fine. I will be working on this and fixing the bug here shortly. Sorry for the wait, I've been tied up with other life stuff, so I've been slower than I would like to be.

**Comment by McSib** [comment]
I also apologize if I come off a little blunt in my previous posts. By no means am I trying to be. Just the VPN thing has been a pain in my but in terms of developing this program. I wish there was a way to fix it, but there isn't at the moment.

**Comment by McSib** [comment]
> I just updated to the latest version, and the error still occurs. The new error in the terminal says
> 
> ```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\e621\io\tag.rs:162:43
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> The log file is included below
> 
> ```
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:23] Printing system information out into log for debug purposes...
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:24] ARCH:           "x86_64"
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:25] DLL_EXTENSION:  "dll"
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:26] DLL_PREFIX:     ""
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:27] DLL_SUFFIX:     ".dll"
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:28] EXE_EXTENSION:  "exe"
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:29] EXE_SUFFIX:     ".exe"
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:30] FAMILY:         "windows"
> 13:35:56 [TRACE] (1) e621_downloader: [src\main.rs:31] OS:             "windows"
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:26] Starting e621 downloader...
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:27] Program Name: e621_downloader
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:28] Program Version: 1.7.0-hotfix.1
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:29] Program Authors: McSib <mcsibsart@gmail.com>
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:30] Program Working Directory: C:\Users\Andrew\Downloads\e_downloader_1.7.0-hotfix.1_release
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:39] Checking if config file exists...
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:47] Checking if tag file exists...
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:61] Login information loaded...
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:62] Login Username: 
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:63] Login API Key: 
> 13:35:56 [TRACE] (1) e621_downloader::program: [src\program.rs:64] Login Download Favorites: true
> 13:35:56 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:54] SenderClient initializing with USER_AGENT_VALUE "e621_downloader/1.7.0-hotfix.1 (by McSib <mcsibsart@gmail.com> on e621)"
> 13:35:56 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:59] Prompt for safe mode...
> 13:35:58 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:72] Safe mode decision: false
> 13:35:58 [TRACE] (1) e621_downloader::program: [src\program.rs:71] Parsing tag file...
> ```

If you can, create a new issue on the issues board with your tag file and log file shown, from there, I can figure out exactly what's happening.

**Comment by McSib** [comment]
With the latest commit pushed to #49, this error is now fixed and no longer happens. If you know how to compile the program with cargo, you can grab that branch and compile it yourself for usage. If you can't, that's okay, this new version should be releasing pretty soon, so please be patient until then. :3

A workaround you can do if you decide to wait is to add another tag to your search. _This second tag must not contain `:`._
