### ISSUE TITLE
Long tag filters cause file paths too long to rename in Windows

### ISSUE THREAD

**Issue by capSAR273** [McSib/e621_downloader#53]
Hi! Great program, but I'm noticing that if a tag line is fairly long the resulting folder name will also contain every tag from the file. This is great for organizing but if it is too long you can't rename it in Windows unless you move it to the root of a drive.

Would it be possible to have an option to remove any "-tagname", or other qualifying tag names from the folder name after the download is complete? I don't think anyone would want to keep the tags they are excluding in the resulting folder name. Thanks

**Comment by McSib** [comment]
I updated the code to shorten the directory to half its length if it crosses 260 (the max path length a Windows path can have). Hopefully this fixes your issue so you can use the program more comfortably. However, I would recommend using the program in a directory closer to the root drive directory. It can improve runtime a little bit and will completely get rid of this issue (or more prevent it from rearing its head again.) Sorry for getting to this so late, thank you for being patient. Have a great day!
