### ISSUE TITLE
parsing error from reading blacklist

### ISSUE THREAD

**Issue by Vantropix** [McSib/e621_downloader#56]
simple issue that will either take 5 minutes or 5 hours to fix
you can't have score:<0 in your blacklist as it can't recognize ":", there is likely more characters.

**Comment by McSib** [comment]
I will be looking into this bug and checking on what's causing it. Sorry for not replying sooner, I've been in college for the last year and had little time to actually work on my projects at the pace I would've wanted.

**Comment by McSib** [comment]
This feature is now implemented, so you should be able to freely use `score` in your blacklist without any problems.
