### ISSUE TITLE
Spamming "No alias was found for rating:safe" and "No alias was found for order:score"

### ISSUE THREAD

**Issue by DestinyPlayer** [McSib/e621_downloader#57]
```
04:28:10 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:379] No alias was found for order:score...
04:28:10 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:380] Printing trace message for why None was returned...
04:28:10 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:381] error decoding response body: invalid type: map, expected a sequence at line 1 column 0
04:28:11 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:379] No alias was found for rating:safe...
04:28:11 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:380] Printing trace message for why None was returned...
04:28:11 [TRACE] (1) e621_downloader::e621::sender: [src\e621\sender\mod.rs:381] error decoding response body: invalid type: map, expected a sequence at line 1 column 0
```
The newest update seems to have caused the log to fill up with these messages during tag list parsing, and as far as I can tell it basically doesn't recognize these anymore.

**Comment by DestinyPlayer** [comment]
There might be some more issues in addition to that, as, in spite of me making sure to try it with different VPN servers (can't do it without one, alas) I keep on getting the same error at the end. I thought that it was just the same "I'm getting caught by a Captcha" error that pops up whenever you use a VPN, but it seems to be too consistent.

This error doesn't pop up in the log, but instead only in the console.
```
thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Error("expected ',' or '}'", line: 3, column: 3)', src\e621\grabber.rs:49:43
```
If it helps, here's my tag list. Maybe I've done something wrong with it? But I can confirm that it did not have any issues with separated tags like this before.
https://pastebin.com/awyzqCGH

**Comment by DestinyPlayer** [comment]
After finally managing to get the old version to not VPN-out, I can confirm that this did not used to happen with the older version, both the Rust error and the "No alias was found" error.

**Comment by McSib** [comment]
Sorry for the late reply to this. I want to preface that I'm in college and have had three classes that's taken up a ton of my time, so I've had little wiggle room to actually go through and look at these issues thoroughly. I'm free for today, so I will be looking through and inspecting what's happening.

**Comment by DestinyPlayer** [comment]
No problem mate, I've been through uni, I know how it eats brains for breakfast.

**Comment by McSib** [comment]
I've been doing physics and linear algebra mixed in with low-level C++ GUI programming. It's been taking a ton of time.

**Comment by McSib** [comment]
So, I know you mentioned finding a version that doesn't cause VPN errors for you anymore, do you mind telling me what release that was? I could take a look to see if there was maybe something I changed that caused a bug I never noticed.

**Comment by DestinyPlayer** [comment]
The current version I'm using is 1.7.0

1.7.1 is the one that breaks.

**Comment by McSib** [comment]
If you still have the log file with the panic crash, could you send that to me? I want to take a look at the full log and see what's happening there.

**Comment by McSib** [comment]
I think I located your issue. This is where the error is reported.


![Image](https://user-images.githubusercontent.com/40368716/207088032-c4f1f1e7-e2a2-40c8-b433-da084e4263a3.png)




![Image](https://user-images.githubusercontent.com/40368716/207086508-e07829e4-ff57-425d-98c7-eae2a5db5f37.png)



![Image](https://user-images.githubusercontent.com/40368716/207086601-7a1ba96a-4484-4220-b56a-7efa6688d8db.png)

The config file was also updated in v1.7.1. It added a new field to the serializing and deserializing. That crash is because it's missing a field, or syntax issues are raised. Your config file should look like this:


![Image](https://user-images.githubusercontent.com/40368716/207087368-f48468dd-37ba-422a-a7ca-22c49ea723bf.png)

**Comment by DestinyPlayer** [comment]
Set the config file up correctly, as far as I can tell
`{
  "downloadDirectory": "test/",
  "fileNamingConventon": "id"
}`
But the result is still a crash.
https://pastebin.com/i8CucLim - Log

**Comment by DestinyPlayer** [comment]
https://pastebin.com/cw9q1zFi
Tested it with md5 instead of id, still the same issue.

**Comment by DestinyPlayer** [comment]
Okay, this time it actually got to the point of actually grabbing links.

Please don't tell me that this entire issue has been there because I've been making the exact same typo for months >>

**Comment by DestinyPlayer** [comment]
Apparently it has in fact been because I've been making the same exact typo for months. Sorry for bothering you >>

**Comment by McSib** [comment]
Happy to see it's working fine now. A quick fix for the future is just deleting the config and letting the program generate a new one (it will include the new fields and such). Happy to see that this wasn't a huge bug happening internally though. Hope you have happy downloads in the future, and enjoy my software without issue again. This new update will be done soonish, just need to do a little more work to ensure everything is fixed and working. 😄
