### ISSUE TITLE
A downloaded image was unable to be saved...

### ISSUE THREAD

**Issue by PrOwOtogen** [McSib/e621_downloader#59]
Everytime, a image can´t be saved, the program shuts down, maybe there´s a way to just skip the image and continue

[e621_downloader.log](https://github.com/McSib/e621_downloader/files/9997318/e621_downloader.log)

**Comment by McSib** [comment]
If you could, can you provide the full unedited log file? There is a lot of information that is given that can give me cues on what might be happening.
