### ISSUE TITLE
Fails to download posts when not using safemode

### ISSUE THREAD

**Issue by ZervoTheProtogen** [McSib/e621_downloader#66]
I assume this has something to do with my blacklist. I checked it and there are no special characters that should be causing it to fail. Here is the output of the command:

20:04:41 [ERROR] Json was unable to deserialize to "serde_json::value::Value"!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

error decoding response body: expected value at line 1 column 1', src/e621/sender/mod.rs:270:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

And the log: [e621_downloader.log](https://github.com/McSib/e621_downloader/files/10200844/e621_downloader.log)
I use arch linux, and the release from the github page as I failed to build it.

EDIT: Forgot to mention that I use a VPN (NordVPN), I tried changing locations as well as disabling it but the result didn't change.

**Comment by ZervoTheProtogen** [comment]
Just tried using the android client app "e1547" on my phone and it seems that it can't connect/fetch from e621.net, it can however fetch from e926 no problem. This would explain why the downloader only works in safemode. I checked a status website and turns out e6 was recently down for a few hours, so I'm guessing that the API is still having problems. I will now close this issue as it was an likely error on e621's side, and not a bug with this software.

**Comment by McSib** [comment]
I'm tagging this and assigning myself just in the event this is something to do with a change in the API. If you still have issues with using my downloader later and are having issues with using and downloading posts due to the same reasons as listed in this post, feel free to reopen the issue and post a comment explaining the situation and giving steps to reproduce the error.
