### ISSUE TITLE
Program crashes with 17:27:41 [TRACE] (1) e621_downloader::e621: [src\e621\mod.rs:113] A downloaded image was unable to be saved... when downloading is_(artist)

### ISSUE THREAD

**Issue by DestinyPlayer** [McSib/e621_downloader#98]
https://hastebin.com/mebocuhofe.yaml - Log

There seems to be some sort of issue with this specific artist, as it consistently crashes on that exact point every single time.

In case it's failing to grab the next artist instead, the next one in the list should be jollyjack.

**Comment by DestinyPlayer** [comment]
It seems to have stopped doing that, I think.

**Comment by DestinyPlayer** [comment]
Okay, it seems to be, indeed, something to do with the is_(artist) tag. I managed to download things past it properly after removing it from the tags list. Once I'm done downloading, I'll see if downloading JUST that tag has the same issue.

**Comment by DestinyPlayer** [comment]
Yup, it's SPECIFICALLY that artist tag for some reason.
https://prnt.sc/4W5tqRH9vgeY - Screenshot of the console error
https://pastebin.com/ZVUseyUi - full error log

**Comment by DestinyPlayer** [comment]
Aand I think I immediately proceeded to solve the issue.

For some reason, the tag copied wrong and there was a hidden invisible character at the end. Not even sure it was a space >>

**Comment by McSib** [comment]
Happy to hear the issue was just a typo. Not sure how an invisible character like that snuck in. Those things always fight with my parser a bit. Hopefully one day I can figure out a fix for it, or find a way to trim them away.
